In [9]:
import numpy as np
a=np.arange(10)
print(a)
a.sum()
#a.transpose()
%copy

[0 1 2 3 4 5 6 7 8 9]
The syntax of the command is incorrect.


In [22]:
b=np.array([range(i,i+3) for i in [2,4,6]])
print(b)
print(b.transpose())

[[2 3 4]
 [4 5 6]
 [6 7 8]]
[[2 4 6]
 [3 5 7]
 [4 6 8]]


In [23]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

# Calculate the Eigenvalues and Eigenvectors of that Matrix
eigenvalues ,eigenvectors=np.linalg.eig(matrix)
print(eigenvalues)
print(eigenvectors)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [27]:
np.linalg.inv(matrix)

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [29]:
matrix.min(axis=1)

array([1, 4, 7])

In [36]:

from selenium import webdriver 
from selenium.webdriver.support.ui import WebDriverWait 
from selenium.webdriver.support import expected_conditions as EC 
from selenium.webdriver.common.keys import Keys 
from selenium.webdriver.common.by import By  
  
# Replace below path with the absolute path 
# to chromedriver in your computer 
driver = webdriver.Chrome('C:/Users/Admin/Downloads/chromedriver') 
  
driver.get("https://web.whatsapp.com/") 
wait = WebDriverWait(driver, 600) 
  
# Replace 'Friend's Name' with the name of your friend  
# or the name of a group  
target = '"Papa"'
  
# Replace the below string with your own message 
string = "Message sent using Python!!!"
  
x_arg = '//span[contains(@title,' + target + ')]'
target = wait.until(EC.presence_of_element_located(( 
    By.XPATH, x_arg))) 
target.click()

input_box=driver.find_element_by_class_name('_13mgZ')

for i in range(10): 
    input_box.send_keys(string + Keys.ENTER) 
    time.sleep(1)


In [9]:
from selenium import webdriver
import getpass
browser=webdriver.Chrome("C:/Users/Admin/Downloads/chromedriver")
browser.get("https://www.facebook.com/")

e = input("Enter your email i.e. linked with facebook:\n")
#Taking the email id from the user and storing it in variable 'e'.
p = getpass.getpass(prompt='Enter your fb password:\n')
#Taking the password from the user and storing it in variable 'e'.
#Note the usage of getpass to keep the password hidden
#But getpass functionality doesn't work on Sypder Console, try Jupyter Notebook for this. 

email = browser.find_element_by_id("email")
email.send_keys(e)
#Sending the email address provided by the user in desired place

password = browser.find_element_by_id("pass")
password.send_keys(p)
#Sending the password provided by the user in desired place

log_in = browser.find_element_by_id("loginbutton")
log_in.click()

Enter your email i.e. linked with facebook:
7888470956
Enter your fb password:
········
